name: deploy

on:
  [push]

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   AZURE_FUNCTIONAPP_PUBLISH_PROFILE
#
# 2. Change these variables for your configuration:
# env:
#   AZURE_FUNCTIONAPP_NAME: sakuraitweetbot # set this to your application's name
#   AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'   # set this to the path to your web app project, defaults to the repository root
#   PYTHON_VERSION: '3.7'                 # set this to the python version to use (supports 3.6, 3.7, 3.8)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Define env variables'
    - shell: bash
    - run: |
        echo "AZURE_FUNCTIONAPP_NAME=sakuraitweetbot" >> $GITHUB_ENV
        echo "AZURE_FUNCTIONAPP_PACKAGE_PATH=." >> $GITHUB_ENV
        echo "PYTHON_VERSION=3.7" >> $GITHUB_ENV

    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: Setup Python $GITHUB_ENV.PYTHON_VERSION Environment
      uses: actions/setup-python@v2
      with:
        python-version: $GITHUB_ENV.PYTHON_VERSION

    - name: 'Resolve Project Dependencies Using Pip'
      shell: bash
      run: |
        pushd './$GITHUB_ENV.AZURE_FUNCTIONAPP_PACKAGE_PATH'
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1.1.4
      id: fa
      with:
        app-name: $GITHUB_ENV.AZURE_FUNCTIONAPP_NAME
        package: $GITHUB_ENV.AZURE_FUNCTIONAPP_PACKAGE_PATH
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
